# 开发环境配置
logging:
  level:
    root: warn
    org.springframework: warn
    com.r2d2.bg: debug
    org.springframework.jdbc.core: warn
    org.springframework.jdbc.datasource: warn



spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/gc4ep?serverTimezone=GMT%2B8
    username: gc4ep
    password: gc4ep
    url: jdbc:mysql://rm-2ze1o8k6649h4217r.mysql.rds.aliyuncs.com:3306/gc4ep?serverTimezone=GMT%2B8

socket:
  port: 10502
