# 开发环境配置
logging:
  level:
    root: warn
    org.springframework: warn
    com.r2d2.bg: debug
    org.springframework.jdbc.core: warn
    org.springframework.jdbc.datasource: warn

server:
  port: 8011
  host: localhost
  #ssl:
    #key-store: classpath:keystore.p12
    #key-store-password: 111111
    #keyStoreType: PKCS12

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gc4ep?serverTimezone=GMT%2B8

